#!/usr/bin/env bash

git clone https://github.com/neovim/neovim.git $HOME/personal/neovim

sudo apt install cmake gettext lua5.1 liblua5.1-0-dev -y
sudo apt install luarocks -y

cd $HOME/personal/neovim
git fetch
git checkout v0.11.2
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
